name: Build suprx

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compiler
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Envoyer le suprx
        uses: actions/upload-artifact@v4
        with:
          name: vitacraft-suprx
          path: build/vitacraft.suprx
